name: learn-github-actions
on: [push]
jobs:
  example-job:
    runs-on: ubuntu-latest
    name: Save output
    steps:
      - shell: bash
        env:
          SECRET_TXT: ${{ secrets.SECRETE_TEST_1 }}
        run: |
          echo $SECRET_TXT
