name: learn-github-actions
on: [push]
jobs:
  example-job:
    runs-on: ubuntu-latest
    name: Save output
    services:
      mysql:
        image: mysql:5.6
        options: >-
          --health-cmd "mysqladmin ping -h localhost"
          --health-interval 20s
          --health-timeout 10s
          --health-retries 10
        env:
          MYSQL_ROOT_PASSWORD: password
    steps:
      - shell: bash
        env:
          SECRET_TXT: ${{ secrets.SECRETE_TEST_1 }}
        run: |
          echo $SECRET_TXT
          docker-compose
